### ISSUE TITLE
Meta: Tracing

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2678]
hyper uses [tracing](https://crates.io/crates/tracing) for logging and events. This issue is meant to be a meta or tracking issue around the overall usage of `tracing` inside hyper. Eventually, users should be able to depend on certain spans and events. Which exactly, we need to figure out.

## Relevant issues

- [x] #2498 
- [ ] Design spans specific to the server
- [ ] Design spans specific to the client
- [x] By hyper 1.0, make `tracing` support "unstable" if not also 1.0

**Comment by taqtiqa-mark** [comment]
@seanmonstar do you want to ignore events that are not in the context of a span?

Using the current code (still early), and the example `client_json`, these spanless events currently look like:

```log
TBC
```

**Comment by taqtiqa-mark** [comment]
Recording some issues related to OpenTelemetry, these do not appear to impact other layers (json, print, jounald).
Context: With OTel none of the data shown above is currently visible.  We are not alone, and existing issues are still open.  As they are resolved the OTel tracing story in Hyper will improve:

- https://github.com/open-telemetry/opentelemetry-specification/issues/1682
- https://github.com/open-telemetry/opentelemetry-specification/issues/2125
- https://github.com/open-telemetry/opentelemetry-rust/issues/625
- https://github.com/tokio-rs/tracing/issues/1531
- https://github.com/tokio-rs/tracing/issues/1481

**Comment by Geal** [comment]
Adding some context on https://github.com/seanmonstar/warp/issues/923: from a server point of view, it would be useful to have a span that is valid from the first byte received to the last byte sent. Otherwise, when using the `Service` trait with a chunked response, a span created in the service will not include any event sent when writing the body. Currently they appear under their own trace id, different from the request's trace id.

Such a span would need to be changed for each new request on an existing connection (in keep alive) for integration with opentelemetry.

I have looked a bit at how it could be implemented, at least for HTTP1, that would require adding a span member to `proto::h1::conn::Conn` and enter the span on every operation. I can make an attempt at it if there is no ongoing work in it right now

**Comment by davidpdrsn** [comment]
@Geal this is exactly how tower-http's [`Trace` middleware](https://docs.rs/tower-http/0.2.0/tower_http/trace/index.html) works. The span it creates lasts from request is received until the entire response body is sent (or earlier if the client doesn't consume the entire body).

**Comment by Geal** [comment]
@davidpdrsn Thanks, that worked perfectly

**Comment by EliSnow** [comment]
Related #56
