### ISSUE TITLE
Meta: Audit public dependencies

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2874]
As part of reaching hyper 1.0, we need to audit the "public" dependencies to make sure that:

- We actually mean for that dependency to be exposed.
- The dependency is stable.

This list might be incomplete, but currently has:

- [x] `http` must reach 1.0
- [x] `http-body` must reach 1.0
- [x] #3319
- [x] `bytes` must be 1.0
- [x] Tokio 1.0 or remove for `hyper::io` traits

**Comment by hawkw** [comment]
I think the `Tokio` 1.0 checkmark should be checked off, given that Tokio's `io` traits are stable :)
